### ISSUE TITLE
new dependency csound-expression-opcodes-0.3.3.1 is not available on hackage/github

### ISSUE THREAD

**Issue by afcady** [spell-music/csound-expression#36]
I can't find the source on github/google either.  There's no apparent way to compile the latest commit (e78943fdcbd015278415bf74564266343a9e2521).

**Comment by anton-k** [comment]
It's generated package. You can make it with `gen-opcodes` package. Install it on your computer and it will create command line utility `gen-opcodes`. You can invoke it and it generate the missing package in the current directory

**Comment by afcady** [comment]
OK, but it remains the case that stack/cabal install from source just does not work.  And there is not even any documentation in README.md to explain what to do when it fails.

At the very least the "Source repository"  field on hackage for the package should say "https://github.com/spell-music/gen-opcodes" instead of being blank.
