### ISSUE TITLE
Humanize examples does not work

### ISSUE THREAD

**Issue by rrottier** [spell-music/csound-expression#37]
Running `dac $ mul (humanVal 0.1 sqrSeq [1, 0.5, 0.2, 0.1] 1) $ white`

from Csound-Air-Envelope

give me the following error:

```
<interactive>:107:12-51:
    Couldn't match type ‘Sig’ with ‘SE Sig’
    Expected type: [Sig] -> Sig -> Sig
      Actual type: HumanizeValueOut ([Sig] -> Sig -> Sig)
    The function ‘humanVal’ is applied to four arguments,
    but its type ‘Sig
                  -> ([Sig] -> Sig -> Sig) -> HumanizeValueOut ([Sig] -> Sig -> Sig)’
    has only two
    In the first argument of ‘mul’, namely
      ‘(humanVal 0.1 sqrSeq [1, 0.5, 0.2, 0.1] 1)’
    In the expression: mul (humanVal 0.1 sqrSeq [1, 0.5, 0.2, 0.1] 1)
```

**Comment by anton-k** [comment]
I see. It should be:

~~~haskell
dac $ (humanVal 0.1 sqrSeq [1, 0.5, 0.2, 0.1] 1) * white
~~~

both of the arguments of `*` have the same type `SE Sig`. I think it over maybe it's worth to introduce special form of `mul` that scales its input with signals that are wrapped in `SE`. The `mul` can only scale with pure signals. 

It's not closed I have to decide for better solution. Thanks for pointing this out.

**Comment by rrottier** [comment]
Thanks, that works.  Agree that the mul is a bit confusing.
