### ISSUE TITLE
Csound-Expression under Windows or Mac?

### ISSUE THREAD

**Issue by ChrizzyM87** [spell-music/csound-expression#38]
Hi! Nice Library! I'm going to hold a presentation about csound-expression and it would be nice to know, if there is a way to run csound-expression under Windows or Mac OS. For myself I'm using Ubuntu, but it would be interesting for the audience. 
Thanks in advance for your answer!
Best regards
Christoph

**Comment by anton-k** [comment]
Hi!

Good to know! I think this can help you: http://hal2016.haskell.org/program.html#kholomiov-tutorial
you can find installation instructions or the workshop.

It should run on Windows and OSX. I did a workshop myself and the major platform among
the audience was OSX and there were no problems among the audience to set the things up.
one problem was after the talk. My lib doesn't run on older versions of GHC (such as 7.8)

An advice: I did a workshop and I have prepared a copy and paste file for the audience (I've shared
it with usb stick for those who came). And I have used it myself to quickly
paste things in the interpreter. That way I could accomplish much more than if I had to type it all.
And you can get nervous on the event and mistype things easily.

I've just wrote the file with the whole ghci session with titles of the slides. Here it is (maybe you can find some useful ideas for your own talk):

https://github.com/anton-k/talks/blob/master/HaL/hal-workshop-copy-and-paste.txt

Good luck with your presentation

I'm just curious what is the place of the event?

**Comment by ChrizzyM87** [comment]
Hi,

Thanks a lot for your answer and your advices! Ich will check them out.

I'm studying electrical engineering in Leipzig (Germany) and we got a
course which is called Computermusic. This is the place of the event ;-)

Best regards
Christoph

**Comment by anton-k** [comment]
What a coincidence! I did a workshop in Leipzig too :)
