### ISSUE TITLE
Installing csound-expression-5.2.2

### ISSUE THREAD

**Issue by ndcroos** [spell-music/csound-expression#49]
When I execute cabal install csound-expression i get the followwing error message? What is going wrong? I'm still new to Haskell. I use Cabal version 1.16 if that helps.

src/Csound/IO.hs:115:25:
    Overlapping instances for RenderCsd (SE a)
      arising from a use of `renderCsdBy'
    Matching instances:
      instance Sigs a => RenderCsd a -- Defined at src/Csound/IO.hs:93:31
      instance Sigs a => RenderCsd (SE a)
        -- Defined at src/Csound/IO.hs:96:31
    In the expression: renderCsdBy opt (fromSource a)
    In an equation for `renderCsdBy':
        renderCsdBy opt a = renderCsdBy opt (fromSource a)
    In the instance declaration for `RenderCsd (Source a)'

src/Csound/IO.hs:118:25:
    Overlapping instances for RenderCsd (SE a)
      arising from a use of `renderCsdBy'
    Matching instances:
      instance Sigs a => RenderCsd a -- Defined at src/Csound/IO.hs:93:31
      instance Sigs a => RenderCsd (SE a)
        -- Defined at src/Csound/IO.hs:96:31
    In the expression: renderCsdBy opt (fromSourceSE a)
    In an equation for `renderCsdBy':
        renderCsdBy opt a = renderCsdBy opt (fromSourceSE a)
    In the instance declaration for `RenderCsd (Source (SE a))'

src/Csound/IO.hs:121:27:
    Overlapping instances for RenderCsd (SE ())
      arising from a use of `renderCsdBy'
    Matching instances:
      instance RenderCsd (SE ()) -- Defined at src/Csound/IO.hs:90:30
      instance Sigs a => RenderCsd a -- Defined at src/Csound/IO.hs:93:31
      instance Sigs a => RenderCsd (SE a)
        -- Defined at src/Csound/IO.hs:96:31
    In the expression: renderCsdBy opt
    In the expression:
      renderCsdBy opt
      $ do { (ui, _) <- unSource src;
             panel ui }
    In an equation for `renderCsdBy':
        renderCsdBy opt src
          = renderCsdBy opt
            $ do { (ui, _) <- unSource src;
                   panel ui }

src/Csound/IO.hs:126:27:
    Overlapping instances for RenderCsd (Source ())
      arising from a use of `renderCsdBy'
    Matching instances:
      instance Sigs a => RenderCsd a -- Defined at src/Csound/IO.hs:93:31
      instance Sigs a => RenderCsd (Source a)
        -- Defined at src/Csound/IO.hs:114:31
      instance RenderCsd (Source ())
        -- Defined at src/Csound/IO.hs:120:30
    In the expression: renderCsdBy opt (joinSource src)
    In an equation for `renderCsdBy':
        renderCsdBy opt src = renderCsdBy opt (joinSource src)
    In the instance declaration for `RenderCsd (Source (SE ()))'
Failed to install csound-expression-5.2.2
cabal: Error: some packages failed to install:
csound-expression-5.2.2 failed during the building phase. The exception was:
ExitFailure 1

**Comment by anton-k** [comment]
What is the version of your GHC?

**Comment by ndcroos** [comment]
The GHC version is 7.6.3.

I assume that the issue is just outdated tools. However, I have trouble with updating Cabal and GHC to newer version.

**Comment by anton-k** [comment]
I'm sorry to say but it's veeery old. 
By the way what's your system? How do you install ghc+cabal?
Maybe I can help you to update the Haskell stuff and move on.

**Comment by ndcroos** [comment]
I use an old laptop that runs Ubuntu 14.04 (Trusty). I installed it a couple of years ago but did not use it. I do not remember how I installed it precisely then. I have tried installing csound-expression with Haskell Platform (following the instruction in the introduction).
According to https://packages.ubuntu.com/trusty/haskell-platform the GHC version is 7.6.3.
I assume I could upgrade Ubuntu and try starting from scratch with installing Haskell. I think my other option is using stack and not Haskell Platform.

**Comment by anton-k** [comment]
Ok, You can install any version of GHC with this PPA

https://launchpad.net/~hvr/+archive/ubuntu/ghc

add PPA and then install as in the instruction. It's very handy to test the progrmas against different GHCs. Also after installation you would need to create a link to the needed version.

My lib currently doesn't support the most modern 8.2. So if you want to try csound-expression it's better to choose GHC 8.0.2, with cabal-install that suits the version of GHC.

I hope this helps!
