### ISSUE TITLE
Segmentation faults

### ISSUE THREAD

**Issue by RichardGarz** [spell-music/csound-expression#56]
Merry Christmas,

I am constantly running into Segmentation faults  with csound-expression.
`dac $ osc 440`
is working correctly, putting the sound on the speakers but pretty much everything I try with scores seems to trigger the segmentation fault for me. Taken from the Readme here:
```
> instr x = return $ osc $ sig x
> dac $ mix $ sco instr (temp 440)
``` 
Already gives me the following:
```
0dBFS level = 32768.0
--Csound version 6.10 (double samples) 2018-01-27 
[commit: none]
libsndfile-1.0.28
UnifiedCSD:  tmp.csd
STARTING FILE
Creating options
Creating orchestra
closing tag
Creating score
rtaudio: ALSA module enabled
rtmidi: ALSA Raw MIDI module enabled

csound command: Segmentation fault
end of score.		   overall amps:      0.0
	   overall samples out of range:        0
0 errors in performance
Elapsed time at end of performance: real: 0.252s, CPU: 0.002s
Prelude Csound.Base> 
```

ghci version: 8.6.2
csound-expression: 5.3.2
OS: ubuntu 64bit
I also tried example files from this repo and they failed too. I try to understand the problem, but can't find the cause for this problem. Any possible solutions or root causes you may know?

**Comment by anton-k** [comment]
Your example runs fine for me. 
I think you need to update the Csound. What version are you using?

```
csound --version
```

**Comment by anton-k** [comment]
Ok, I can see the version is:
```
--Csound version 6.10 (double samples) 2018-01-27 
```

I'm using 

```
--Csound version 6.10 (double samples) Dec 18 2017
```
right now, but it's good to update for me too I guess..
but on this version your example works

**Comment by RichardGarz** [comment]
I update to 6.13 (Beta) and now its working for me too. Thanks for the quick hint :)
