### ISSUE TITLE
Virtual midi controller and keyboard from tutorial examples are not working on macOs?

### ISSUE THREAD

**Issue by blinky3713** [spell-music/csound-expression#62]
In following the tutorial there are times when you are using a virtual keyboard or midi controller for input. On macOs I have used the installer available from the latest version of [csound 16.5.0](https://github.com/csound/csound/releases/tag/6.15.0) but whenever I run examples in ghci I get a blank window like

<img width="612" alt="Screen Shot 2021-01-24 at 11 08 19 AM" src="https://user-images.githubusercontent.com/31280145/105640846-2f03fc00-5e35-11eb-91f3-5278ab9468ad.png">

However, if you just randomly click around in this blank window, you can discover that the keys or sliders are actually working, in the sense that you can still create or manipulate sound. As far as I can tell, the appropriate flags are being set:

```bash
...
Creating score
rtaudio: PortAudio module enabled ...
using callback interface
rtmidi: PortMIDI module enabled
...
```
I wonder if it has something to do with the release note:

> Starting from this release, no third-party graphic frontends are shipped with the installation packages on MacOs and Windows.

Does anyone else have this problem or a solution for it?

**Comment by anton-k** [comment]
Unfortunately it seems to be a problem with FLTK on MacOS, 
FLTK is used as default lib to render UIs in Csound and it seems to be broken on Mac. 

this is related: https://github.com/csound/csound/issues/1325

**Comment by anton-k** [comment]
I can not fix it on Haskell level

**Comment by anton-k** [comment]
Thanks for bringing this up. I should mention it in the docs.
I can not test the code on mac.

**Comment by blinky3713** [comment]
thanks for looking into it!
