### ISSUE TITLE
Missing FLPanel

### ISSUE THREAD

**Issue by georgefst** [spell-music/csound-expression#69]
I'm trying to run [the pedalboard example](https://github.com/spell-music/csound-expression/blob/master/tutorial/chapters/FxFamily.md#example-virtual-pedalboard), but I've hit the issue from #13 (`Unexpected untyped word FLpanel when expecting a variable`). Unfortunately, I'm on Arch and there's no `csound-gui` package (although even the apt one seems like [it may no longer do what's needed](https://bugs.launchpad.net/ubuntu/+source/csound/+bug/1011263)).

I'll have to investigate with the `csound` maintainers and Arch packagers to see what's going on here.

**Comment by georgefst** [comment]
> I'll have to investigate with the `csound` maintainers and Arch packagers to see what's going on here.

See csound/csound#907.

**Comment by anton-k** [comment]
Thanks to mention that as I've switched to Manjaro recently. Now I've also discovered that fltak GUI does not work.
Which is a pity... I've asked on Csound forum for help. Maybe other Arch/manjaro users can reach out and help us with that.

**Comment by georgefst** [comment]
> I've asked on Csound forum for help.

Thanks! Could you post a link to that? I'd like to follow, but couldn't find it.

**Comment by anton-k** [comment]
https://listserv.heanet.ie/cgi-bin/wa?A2=ind2201&L=CSOUND&P=70415

**Comment by anton-k** [comment]
They reply that it was moved to another repo and probably should be built from sources. Or maybe there is Arch project for csound-plugins

**Comment by anton-k** [comment]
The repo is here: https://github.com/csound/plugins

**Comment by georgefst** [comment]
As I mentioned in https://github.com/csound/csound/issues/907#issuecomment-1010446003, there's no Arch csound-plugins package, even though weirdly there's evidence that one may once have existed.

And I had difficulty with building from source, although I may look in to it further. Have you tried?

**Comment by anton-k** [comment]
Ok I could install it from sources. Here is the instruction for it:

* install `fltk` package

* Find out your csound installation path:

```
> whereis csound
csound: /usr/local/bin/csound /usr/local/lib/csound /usr/include/csound
```
For me the path prefix is `/usr/local/lib`

* clone [plugins repo](https://github.com/csound/plugins). Make sure that you are on latest develop branch

* Follow instructions on their installation guide but also make sure to setup the flags `CMAKE_INSTALL_PREFIX` and `USE_LIB64`
    on cmake. For me it looks:
    
    ```
    cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DUSE_LIB64=0 ../
    ```
* After `sudo make install` we can check that it was installed alright by command:

   ```
   > csound -z1 2>&1 | grep FLpanel
   ```
    It should produce output.
 
For me problem was that I used it on master branch and master branch has a bug in installation copy path.

**Comment by georgefst** [comment]
Thank you! That'll tide me over until it's properly packaged again.

**Comment by georgefst** [comment]
PS. This library is awesome! And, in case you've never tried it, the visual stuff (e.g. the virtual pedalboard example) works beautifully with a touch screen.

**Comment by anton-k** [comment]
Thanks for kind words, I happy to know!
