### ISSUE TITLE
How to set virtual keyboard size?

### ISSUE THREAD

**Issue by georgefst** [spell-music/csound-expression#73]
When running e.g. `vdacBy $ atMidi polySynth`, is there any way to set the window dimensions? I can't even use my window manager to adjust them. I was hoping to be able to use my touchscreen to play the keyboard, but at the default size the keys are too small for this to really be feasible.

I was hoping that something like `vdacBy (def{csdScaleUI = Just (2,2)}) $ atMidi polySynth` would double the size, but it does not. No values I put there have any visible effect.

**Comment by georgefst** [comment]
Actually, relatedly, is there any way to configure other parameters? e.g. the number of keys?

**Comment by anton-k** [comment]
I doubt it. Here is docs on virtual keyboard:

http://www.csounds.com/manual/html/MidiTop.html

**Comment by anton-k** [comment]
I suggest to use some linux virtual keyboard or virtual midi on your system and connect it to csound

**Comment by georgefst** [comment]
Thanks, you're probably right. I'll look in to how to do that.
