### ISSUE TITLE
Using it with tidal cycle

### ISSUE THREAD

**Issue by guillaume-leo** [spell-music/csound-expression#75]
First of all congratulation for this project. I discovered it recently and it looks really wonderful.
Do you think it could be easy to use it with tidal cycles? The goal for me would be to play synths from tidal, and to control them.

**Comment by anton-k** [comment]
Hi! Thanks for feedback!
I havn't used tidal-cycles. I know that it sends osc or midi messages to dedicated sampler. 
CE supports both midi and osc, so if you know the tidal format it can be possible.
I used OSC it should work.

**Comment by guillaume-leo** [comment]
That great, I was thinking that as the two libraries are coded in haskell, one could communicate to the other without passing by OSC.
I know then that is definitely possible by OSC, I've already done it in Max/Msp we just need to reschedule the events when received... It should be straightforward to do even if I don't know Haskell (I hope :)).
I will make some experiments and I'll keep you in touch.
