### ISSUE TITLE
Novice Struggling with finding dependencies

### ISSUE THREAD

**Issue by CMorrison82z** [spell-music/csound-expression#92]
OS: EndeavourOS

Using `cabal repl` with:
`    build-depends:    base ^>=4.17.2.1
                    , csound-expression >= 5.4.3
                    , csound-catalog
`

installed `csound` and `WildMIDI` from the AUR. (Note I did NOT install cabal using AUR as that's known to cause issues)

I'm currently unable to get sound from `vdac midi`, and from temporal-media module (used in the "Scores" section). The virtual keyboard appears, but produces no sound

I suspect I'm missing some kind of dependency ?

**Comment by anton-k** [comment]
Sorry for late reply this caused by this bug: #93 
I'm going to fix it in upcoming release.

**Comment by anton-k** [comment]
I've tried vdac on new version and it works. Probably it was silenced by the bug in renderer.

**Comment by anton-k** [comment]
It's fixed on master. I've uploded new version to hackage also.
