### ISSUE TITLE
Csound-gui

### ISSUE THREAD

**Issue by CMorrison82z** [spell-music/csound-expression#96]
I cannot find the `csound-gui` package dependency, or an analogous package in the AUR. I checked the APT packages for `csound-gui` via https://packages.ubuntu.com/ and couldn't find it there (granted, I don't know how APT indexes for packages)

**Comment by anton-k** [comment]
I've searched on this topic. FLTK package seems to be deprecated on csound side, 
the easiest option is to try to find and install an older version of Csound, say 6.15.

**Comment by anton-k** [comment]
I recommend to use midi controller or control with OSC

**Comment by anton-k** [comment]
For example this page mentions 6.13 version on 20.04 lts https://packages.ubuntu.com/focal/csound

**Comment by anton-k** [comment]
UI was a very cool feature it's sad that it's got deprecated.

**Comment by CMorrison82z** [comment]
No worries. I should be fine without it, I just thought I was doing something wrong. Cheers !
